services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
  
  backend:
    build:
      context: ./back
    container_name: scantrad-back
    environment:
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "8000:8000"
    volumes:
      - ./transformer/:/app/transformer:ro
    depends_on:
      - mongo

  frontend:
    build:
      context: ./front
    container_name: scantrad-front
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
    name: scantrad_network

